# Generated by Django 3.1.7 on 2021-03-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210226_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
